name: GitHub Actions Demo

on:
  push:
    branches:
      - main
      
  pull_request:
    branches:
      - main    
  
  schedule:
    - cron: "15 18 * * SUN"
    
    
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - run: echo "The job was triggered by ${{github.event_name}}"
  
